### PR TITLE
Url exclude

### PR DESCRIPTION
**Pull request by jgreben**
Corrects the test syntax for PUT and DESTROY. Make db seed data and Re-enables the coveralls lint.

### CODE REVIEW

**Comment by jgreben** [comment]
@shelleydoljack @dlrueda I won't use this branch anymore after this pull request. All the tests are passing now!

**Comment by dlrueda** [comment]
Do all the localhost:3000/url_exclusions actions work: create a new one, edit, destroy?  Call me paranoid but I want to know if the actual web site works, beyond the rake tests.

**Comment by jgreben** [comment]
Ok this fixes the destroy method. Who knew that you needed javascript fir this to work...

**Comment by dlrueda** [comment]
Crazy.  And edit works too?  That one was broken also, and I imagine having javascript probably fixes this as well, but can you double-check?  Sorry, so paranoid (but I was right last time....)

**Comment by jgreben** [comment]
Paranoid!

**Comment by dlrueda** [comment]
Absolutely!

**Comment by jgreben** [comment]
It's all good to go! Edit too.
👍

**Comment by dlrueda** [comment]
Groovy!

**Pull request merged**
